### ISSUE TITLE
Feature Request: full automatic installation

### ISSUE THREAD

**Issue by haifengkao** [mleduque/modda#16]
I think the installation can be fully automatic if modda provides a way to record the the question and answer from the user. It should only stop when it encountered unanswered questions.

If it can be fully automatic, we will have wabbajack for BG.

**Comment by mleduque** [comment]
I acknowledge your request and consider it sensible.
It's probably possible to have something like that though I couldn't tell exactly in what form.
But I probably won't be able to look at it in the short term.
