### ISSUE TITLE
Mac os bug: incorrect PROGNAME

### ISSUE THREAD

**Issue by haifengkao** [mleduque/modda#31]
```
pub fn read_settings() -> Result<Config> {
    let yaml_name = format!("{prog_name}.yml", prog_name = PROGNAME);
```
the PROGNAME on Mac OS is modda-lib
not modda

solution:
1. hardcodes PROGNAME to modda on Mac OS
2. update the documentation to use ~/Application Support/modda-lib/modda-lib.yml as the config path

**Comment by mleduque** [comment]
Ah yes thank you I broke that and fixed it locally but never pushed the fix.
