### ISSUE TITLE
Mac os bug: incorrect local "weidu" name

### ISSUE THREAD

**Issue by haifengkao** [mleduque/modda#32]
```
fn weidu_command(config: &Config, check_exist: bool) -> Result<String> {
    use crate::progname::PROGNAME;

    match &config.weidu_path {
        Some(path) => {
            let expanded = shellexpand::tilde(path).to_string();
            println!("expanded path: {}", expanded);
            if check_exist && !PathBuf::from(&expanded).exists() {
                bail!("file at '{}' doesn't exist. This is the weidu_path config in ${PROGNAME} settings file (${PROGNAME}.yaml)", path)
            }
            Ok(expanded)
        }
        None => Ok("weidu".to_string()),
    }
}
```

On Mac OS 

// works
Command::new("./weidu");

// not works
Command::new("weidu");
{ code: 2, kind: NotFound, message: "No such file or directory" })

// works
Command::new("ls");

**Comment by mleduque** [comment]
Using `./weidu` would force the weidu executable to be in the current directory.
While perfectly possible this should not become a requirement.
The default is to use weidu on the path if available.
In case it's not on the path there is the option of configuring the path in the config file (which was broken recently as you noticed).
Checking if weidu is on the path is not an easy thing to do (it could probably mean trying to launch and detecting a failure).
I'll keep this issue open in case I find a way to offer a good enough solution.

**Comment by haifengkao** [comment]
how about returning "./weidu" if weidu exists in the current directory? and return "weidu" otherwise

**Comment by mleduque** [comment]
Yes, I was reluctant but we're running from the game dir anyway so if weidu is here it's voluntary. So this might not be a bad idea finally.

**Comment by mleduque** [comment]
I think Ithat should fix it but I have more checks to do
